# Generated by Django 2.1.8 on 2020-12-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xuanxing', '0001_initial'),
        ('products', '0001_initial'),
        ('testm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xuanxing.Index', verbose_name='案例(三级指标)名称'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testm.Projects', verbose_name='测试项目名称'),
        ),
        migrations.AddField(
            model_name='sp_time',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testm.Projects', verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='reports',
            name='group_part',
            field=models.ManyToManyField(blank=True, db_table='report_groups', related_name='report_group', to='testm.Reports_groups', verbose_name='小组组成'),
        ),
        migrations.AddField(
            model_name='reports',
            name='prod_vend',
            field=models.ManyToManyField(blank=True, db_table='reports_prods', related_name='report_prod', to='products.Products', verbose_name='候选选型产品供应商'),
        ),
        migrations.AddField(
            model_name='reports',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_project', to='testm.Projects', verbose_name='测试项目名称'),
        ),
        migrations.AddField(
            model_name='reports',
            name='test_conclusion',
            field=models.ManyToManyField(blank=True, db_table='products_conclusion', related_name='prod_conclusion', to='testm.Conclusion', verbose_name='测试结论'),
        ),
        migrations.AddField(
            model_name='reports',
            name='test_time',
            field=models.ManyToManyField(blank=True, db_table='report_executes', related_name='report_execute', to='testm.Executes', verbose_name='测试时间'),
        ),
        migrations.AddField(
            model_name='projects',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to='xuanxing.ManageUser', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='deal_user',
            field=models.ManyToManyField(db_table='deal_users', related_name='dealname', to='xuanxing.ManageUser', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(db_table='members_users', related_name='membersname', to='xuanxing.ManageUser', verbose_name='参与人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='product_subclass',
            field=models.ManyToManyField(db_table='sub_class', related_name='subclass', to='xuanxing.ProductsType', verbose_name='产品子类'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_speed',
            field=models.ManyToManyField(db_table='pro_sp', related_name='pro_sp', to='testm.Pro_speed', verbose_name='项目进度'),
        ),
        migrations.AddField(
            model_name='projects',
            name='vend_prod',
            field=models.ManyToManyField(db_table='projects_prods', related_name='project_prod', to='xuanxing.ProductsDetail', verbose_name='厂商名称'),
        ),
        migrations.AlterUniqueTogether(
            name='executes',
            unique_together={('execute_name',)},
        ),
        migrations.AddField(
            model_name='dongtai',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testm.Projects', verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='vend_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conclusion_product', to='products.Products', verbose_name='供应商产品'),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('case_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='reports',
            unique_together={('report_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('project_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='conclusion',
            unique_together={('vend_product',)},
        ),
    ]
