# Generated by Django 2.1.8 on 2020-12-28 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filesize', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(default='无', max_length=200)),
                ('upload_filename', models.CharField(default='', max_length=200)),
                ('status', models.SmallIntegerField(choices=[(1, '未上传'), (2, '已上传'), (3, '审核通过'), (4, '审核不通过'), (5, '不涉及')], default=1)),
                ('pro_name', models.CharField(default='无', max_length=200)),
                ('vend_name', models.CharField(default='无', max_length=200)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期')),
                ('download_time', models.CharField(max_length=200)),
                ('remark', models.TextField(verbose_name='备注')),
                ('check_remark', models.TextField(default='', verbose_name='审核备注')),
                ('flag', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('operation', models.CharField(max_length=200, verbose_name='操作详情')),
            ],
        ),
    ]
