# Generated by Django 2.1.8 on 2020-12-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xuanxing', '0001_initial'),
        ('document', '0001_initial'),
        ('testm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xuanxing.ManageUser', verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='doc',
            name='pro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testm.Projects', verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='doc',
            name='vend_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xuanxing.ProductsDetail', verbose_name='厂商名称'),
        ),
    ]
