from django.db import models
from django.contrib.auth.models import User,Group
# Create your models here.

class Pros(models.Model):
    proname = models.CharField(max_length=200,default="无",unique=True)
    prostatus = models.CharField(max_length=200,default="无")
    chargeperson = models.CharField(max_length=200,default="未指定")
    participant = models.CharField(max_length=200,default='未指定')
    createtime = models.DateField()
    createprouser = models.CharField(max_length=50,default='无')
    status = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.proname)


class Input(models.Model):
    tag = models.ForeignKey(User,on_delete=models.CASCADE)
    pro = models.ForeignKey(Pros,on_delete=models.CASCADE)
    input_1 = models.CharField(max_length=200,default='')
    input_2 = models.CharField(max_length=200,default='')
    input_3 = models.CharField(max_length=200,default='')
    input_4 = models.CharField(max_length=200,default='')
    input_5 = models.CharField(max_length=200,default='')
    input_6 = models.CharField(max_length=200,default='')
    input_7 = models.CharField(max_length=200,default='')
    input_8 = models.CharField(max_length=200,default='')
    input_9 = models.CharField(max_length=200,default='')
    input_10 = models.CharField(max_length=200,default='')
    input_11 = models.CharField(max_length=200,default='')
    input_12 = models.CharField(max_length=200,default='')
    input_13 = models.CharField(max_length=200,default='')
    input_14 = models.CharField(max_length=200,default='')
    input_15 = models.CharField(max_length=200,default='')
    input_16 = models.CharField(max_length=200,default='')
    input_17 = models.CharField(max_length=200,default='')
    input_18 = models.CharField(max_length=200,default='')
    input_19 = models.CharField(max_length=200,default='')
    input_20 = models.CharField(max_length=200,default='')
    input_21 = models.CharField(max_length=200,default='')
    input_22 = models.CharField(max_length=200,default='')
    input_23 = models.CharField(max_length=200,default='')
    input_24 = models.CharField(max_length=200,default='')
    input_25 = models.CharField(max_length=200,default='')
    input_26 = models.CharField(max_length=200,default='')
    input_27 = models.CharField(max_length=200,default='')
    input_28 = models.CharField(max_length=200,default='')
    input_29 = models.CharField(max_length=200,default='')
    input_30 = models.CharField(max_length=200,default='')
    input_31 = models.CharField(max_length=200,default='')
    input_32 = models.CharField(max_length=200,default='')
    input_33 = models.CharField(max_length=200,default='')
    input_34 = models.CharField(max_length=200,default='')
    input_35 = models.CharField(max_length=200,default='')
    input_36 = models.CharField(max_length=200,default='')
    input_37 = models.CharField(max_length=200,default='')
    input_38 = models.CharField(max_length=200,default='')
    input_39 = models.CharField(max_length=200,default='')
    input_40 = models.CharField(max_length=200,default='')
    input_41 = models.CharField(max_length=200,default='')
    input_42 = models.CharField(max_length=200,default='')
    input_43 = models.CharField(max_length=200,default='')
    input_44 = models.CharField(max_length=200,default='')
    input_45 = models.CharField(max_length=200,default='')
    input_46 = models.CharField(max_length=200,default='')
    input_47 = models.CharField(max_length=200,default='')
    input_48 = models.CharField(max_length=200,default='')
    input_49 = models.CharField(max_length=200,default='')
    input_50 = models.CharField(max_length=200,default='')
    input_51 = models.CharField(max_length=200,default='')
    input_52 = models.CharField(max_length=200,default='')
    input_53 = models.CharField(max_length=200,default='')
    input_54 = models.CharField(max_length=200,default='')
    input_55 = models.CharField(max_length=200,default='')
    input_56 = models.CharField(max_length=200,default='')
    input_57 = models.CharField(max_length=200,default='')
    input_58 = models.CharField(max_length=200,default='')
    input_59 = models.CharField(max_length=200,default='')
    input_60 = models.CharField(max_length=200,default='')
    input_61 = models.CharField(max_length=200,default='')
    input_62 = models.CharField(max_length=200,default='')
    input_63 = models.CharField(max_length=200,default='')
    input_64 = models.CharField(max_length=200,default='')
    input_65 = models.CharField(max_length=200,default='')
    pub_date = models.DateTimeField('date published')
    mark = models.CharField(max_length=200,default='无')
    csbj = models.FileField(upload_to='file',default='无')
    csdx = models.FileField(upload_to='file',default='无')
    xxxq = models.FileField(upload_to='file',default='无')
    tgxyq = models.FileField(upload_to='file',default='无')
    pjxyq = models.FileField(upload_to='file',default='无')
    csal = models.FileField(upload_to='file',default='无')
    hxxxgys = models.FileField(upload_to='file',default='无')
    cssj = models.FileField(upload_to='file',default='无')
    csdd = models.FileField(upload_to='file',default='无')
    cslc = models.FileField(upload_to='file',default='无')
    cshj = models.FileField(upload_to='file',default='无')
    csjg = models.FileField(upload_to='file',default='无')
    csjilu = models.FileField(upload_to='file',default='无')
    csjlun = models.FileField(upload_to='file',default='无')


    def __str__(self):
        return str(self.tag)



'''class User(models.Model):
    username = models.CharField(max_length=16,unique=True,default="test")
    password = models.CharField(max_length=32,default="123456")
    age = models.SmallIntegerField(default=0)
    gender = models.BooleanField(default=0)
    birth = models.DateField(default='无')
    def __str__(self):
        return self.username,self.password,self.age,self.gender,self.birth
'''
