# Generated by Django 2.1.8 on 2020-12-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100, verbose_name='产品(设备)名称')),
                ('vend_name', models.CharField(max_length=100, verbose_name='厂商名称')),
                ('technical_index', models.TextField(blank=True, null=True, verbose_name='技术指标')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'db_table': 'products_t',
            },
        ),
        migrations.CreateModel(
            name='ProductsClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_subclass', models.CharField(max_length=100, verbose_name='产品子类')),
                ('vend_strategy', models.TextField(verbose_name='厂商策略')),
                ('life_cycle_state', models.CharField(max_length=5, verbose_name='生命使用周期')),
                ('performance_classification', models.CharField(max_length=5, verbose_name='性能分类')),
                ('main_specifications', models.TextField(null=True, verbose_name='主要技术指标')),
                ('deployment_scope', models.CharField(max_length=100, verbose_name='部署范围')),
                ('application_scenario', models.TextField(blank=True, verbose_name='应用范围')),
                ('recommended_production_life', models.CharField(default='无限期', max_length=100, verbose_name='建议生产使用年限')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品分类信息',
                'verbose_name_plural': '产品分类信息',
                'db_table': 'product_class_t',
            },
        ),
        migrations.CreateModel(
            name='ProductsLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_type_name', models.CharField(max_length=20, verbose_name='产品位置名称')),
            ],
            options={
                'verbose_name': '产品位置字典表',
                'verbose_name_plural': '产品位置表',
                'db_table': 'product_location_t',
            },
        ),
        migrations.CreateModel(
            name='ProductsTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_type_name', models.CharField(max_length=50, verbose_name='产品类型名称')),
                ('location_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductsLocation', verbose_name='产品位置')),
            ],
            options={
                'verbose_name': '产品类型字典表',
                'verbose_name_plural': '产品类型字典表',
                'db_table': 'product_types_t',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productslocation',
            unique_together={('location_type_name',)},
        ),
        migrations.AddField(
            model_name='productsclass',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsLocation', verbose_name='产品位置'),
        ),
        migrations.AddField(
            model_name='productsclass',
            name='prod_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsTypes', verbose_name='产品类型'),
        ),
        migrations.AddField(
            model_name='products',
            name='prod_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductsClass', verbose_name='产品类别'),
        ),
        migrations.AlterUniqueTogether(
            name='productstypes',
            unique_together={('location_type', 'prod_type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='productsclass',
            unique_together={('location_type', 'prod_type', 'prod_subclass', 'performance_classification')},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('prod_name', 'vend_name')},
        ),
    ]
